<?php 
$poblaciones = ARRAY(
    NEW PoblacionEnvio("AGUAS", 23.6),
    NEW PoblacionEnvio("ALBERO ALTO", 12.3),
    NEW PoblacionEnvio("ALBERO BAJO", 13.9),
    NEW PoblacionEnvio("ALERRE", 6.5),
    NEW PoblacionEnvio("ALMUDÉVAR", 22.7),
    NEW PoblacionEnvio("ALMUNIENTE", 27.8),
    NEW PoblacionEnvio("ANGÜÉS", 22.6),
    NEW PoblacionEnvio("ANIÉS", 26.4),
    NEW PoblacionEnvio("ANTILLÓN", 29.3),
    NEW PoblacionEnvio("APIÉS", 11.3),
    NEW PoblacionEnvio("ARBANIÉS", 15.6),
    NEW PoblacionEnvio("ARGABIESO", 16.6),
    NEW PoblacionEnvio("AYERA", 12.6),
    NEW PoblacionEnvio("AYERBE", 29.2),
    NEW PoblacionEnvio("BANASTAS", 7.8),
    NEW PoblacionEnvio("BANDALIÉS", 10.4),
    NEW PoblacionEnvio("BARBUÉS", 20.8),
    NEW PoblacionEnvio("BARLUENGA", 13.9),
    NEW PoblacionEnvio("BELLESTAR DEL FLUMEN", 6.8),
    NEW PoblacionEnvio("BESPÉN", 29.3),
    NEW PoblacionEnvio("BLECUA", 25.9),
    NEW PoblacionEnvio("BOLEA", 21.8),
    NEW PoblacionEnvio("BUÑALES", 11.6),
    NEW PoblacionEnvio("CASBAS DE HUESCA", 28.3),
    NEW PoblacionEnvio("CASTEJÓN DE ARBANIÉS", 15.9),
    NEW PoblacionEnvio("CASTILLO POMPIÉN", 7.8),
    NEW PoblacionEnvio("CHIBLUCO", 16.2),
    NEW PoblacionEnvio("CHIMILLAS", 6.5),
    NEW PoblacionEnvio("CURBE", 30.3),
    NEW PoblacionEnvio("COSCULLANO", 18.6),
    NEW PoblacionEnvio("ESQUEDAS", 15.2),
    NEW PoblacionEnvio("FORNILLOS", 9.1),
    NEW PoblacionEnvio("FORNILLOS DE APIÉS", 9.0),
    NEW PoblacionEnvio("GRAÑÉN", 23.7),
    NEW PoblacionEnvio("HUESCA", 4.0),
    NEW PoblacionEnvio("IBIECA", 23.5),
    NEW PoblacionEnvio("IGRIES", 9.9),
    NEW PoblacionEnvio("LASCASAS", 8.1),
    NEW PoblacionEnvio("LIERTA", 16.1),
    NEW PoblacionEnvio("LIESA", 18.4),
    NEW PoblacionEnvio("LOARRE", 29.3),
    NEW PoblacionEnvio("LOPORZANO", 9.2),
    NEW PoblacionEnvio("LOSCORRALES", 25.3),
    NEW PoblacionEnvio("LUPIÑEN-ORTILLA", 25.0),
    NEW PoblacionEnvio("MONFLORITE", 7.6),
    NEW PoblacionEnvio("NOVALES", 17.1),
    NEW PoblacionEnvio("NUENO", 16.5),
    NEW PoblacionEnvio("PIRACÉS", 19.2),
    NEW PoblacionEnvio("PLASENCIA DEL MONTE", 18.3),
    NEW PoblacionEnvio("POMPENILLO", 6.9),
    NEW PoblacionEnvio("QUICENA", 4.6),
    NEW PoblacionEnvio("SALILLAS", 25.1),
    NEW PoblacionEnvio("SANGARRÉN", 15.1),
    NEW PoblacionEnvio("SASA DEL ABADÍACO", 12.3),
    NEW PoblacionEnvio("SESA", 22.6),
    NEW PoblacionEnvio("SIÉTAMO", 12.4),
    NEW PoblacionEnvio("SIPÁN", 14.8),
    NEW PoblacionEnvio("TABERNAS DEL ISUELA", 10.2),
    NEW PoblacionEnvio("TARDIENTA", 28.5),
    NEW PoblacionEnvio("TIERZ", 5.4),
    NEW PoblacionEnvio("TRAMACED", 28.3),
    NEW PoblacionEnvio("VALFONDA DE SANTA ANA", 25.6),
    NEW PoblacionEnvio("VELILLAS", 18.1),
    NEW PoblacionEnvio("VICIÉN", 13.4),
    NEW PoblacionEnvio("YÉQUEDA", 6.4)    
   );
/*
    $i=0;
    while($i<  count($poblaciones)){
        print_r($poblaciones[$i]);
        echo"<br/>";
        $i++;
    }*/